# Portfolioprüfungen

## Bewertungsbogen

Ein generischer Bewertungsbogen für Module mit Portfolioprüfungen bestehend aus semesterbegleitenden Abgaben (Exercises) und einer Semesterendabgabe findet sich hier:

[Bewertungsvorlage Kurse EX + IMP](./data/bchwtz-XXXX-results-INTERN.xlsx)


## Modulbeschreibungen

### RPRG

Programmierung für statistische Datenanalyse

Programming for statistical Data Analysis

+----------------------------------------+-----------------------------+
| **Prüfungsnummer**                     | xxx                         |
+----------------------------------------+-----------------------------+
| **Modulverantwortung**                 | Prof. Dr. Benjamin Buchwitz |
+----------------------------------------+-----------------------------+
| **Sprache**                            | Deutsch                     |
+----------------------------------------+-----------------------------+
| **ECTS**                               | 6                           |
+----------------------------------------+-----------------------------+
| **Workload / Kontakt / Selbststudium** | 180 h / 13 h / 167 h        |
+----------------------------------------+-----------------------------+
| **SWS**                                | 4                           |
+----------------------------------------+-----------------------------+
| **Semester**                           | Winter                      |
+----------------------------------------+-----------------------------+
| **Lehrform**                           | Vorlesung, Übung            |
+----------------------------------------+-----------------------------+
| **Gruppengröße**                       | 20                          |
+----------------------------------------+-----------------------------+
| **Studiengang**                        | Data Science (Master)       |
+----------------------------------------+-----------------------------+
| **Teilnahmevoraussetzung**             | \-                          |
+----------------------------------------+-----------------------------+
| **Prüfungsvorleistung**                | \-                          |
+----------------------------------------+-----------------------------+
| **Prüfungsform**                       | Portfolio                   |
|                                        |                             |
|                                        | -   Implementierung (50%)   |
|                                        | -   Fallstudie (50%)        |
+----------------------------------------+-----------------------------+

**Lernergebnisse:** Die Studierenden sind in der Lage, statistische Datenanalysen in der Programmierumgebung R durchzuführen. Sie haben profunde R-Programmierkenntnisse und können die grundlegenden Datenstrukturen anwendungsgerecht und effizient einsetzen. Sie können weiterhin inhomogene mehrdimensionale Datenbestände auswerten und visualisieren. Sie sind außerdem sowohl mit „Tidyverse" als auch mit weiterführenden objektorientierten und funktionalen Konzepten der Programmiersprache R vertraut.

**Inhalte:** In diesem Modul wird ausführlich auf die frei verfügbare (open source) Programmierumgebung R eingegangen. Kern dieser Programmierumgebung ist die Skriptsprache R, die speziell für statistische Berechnungen und zur Datenvisualisierung entwickelt wurde. Viele gängige statistische Methoden, Analyseprozesse und Visualisierungen lassen sich mit einfachen Mitteln in R durchführen. Zahlreiche Erweiterungen existieren für die unterschiedlichsten Anwendungsgebiete in Form von Zusatzpaketen. R hat sich in der Wirtschaft und auch in der Wissenschaft in den letzten Jahren als eine der Standardsprachen im Bereich der statistischen Datenanalyse und Visualisierung etabliert. In diesem Modul wird zuerst eine solide Einführung in die Sprache R gegeben. Insbesondere werden die grundlegenden Datenstrukturen aus der Kernsprache wie Vektor, Matrix, Array, List und Data Frame in R ausführlich behandelt und es wird gezeigt, wie sie effizient und flexibel eingesetzt werden können. Darauf aufbauend wird in „Tidyverse" eingeführt. Tidyverse ist eine Sammlung von aufeinander abgestimmten R-Paketen, die es ermöglichen, in einer systematischen Weise viele Problemstellungen aus den Bereichen Datenaufbereitung und Datenanalyse effektiv zu lösen. Einen zusätzlichen Themenschwerpunkt bilden unterschiedliche Visualisierungsmöglichkeiten multidimensionaler Datenbestände. Überdies werden weiterführende Sprachkonzepte in R untersucht. Eingegangen wird hierbei sowohl auf objektorientierte als auch auf funktionale Ansätze in R.

**Literatur:**

Matloff, Norman: The Art of R Programming : A Tour of Statistical Software Design, Starch Press Wickham, Hadley und Grolemund, Garrett : R für Data Science : Daten importieren, bereinigen, umformen, modellieren und visualisieren, O'Reilly Wickham, Hadley: Advanced R, CRC Press

## Bachelor

*Statistics*

-   X

*R Programming*

-   Implementierung (50%)
-   Fallstudie (50%)

*Campus Experiments* (WPM)

-   Dokumentation (50%)
-   Präsentation (50%)

*Data Driven Business* (WPM)

-   Dokumentation (50%)
-   Präsentation (50%)

*Statistical Modeling*

-   Präsentation (30%)
-   Fallstudie (70%)

*Forecasting and Control*

-   Implementierung (50%)
-   Fallstudie (50%)

## Master

*Programmierung für statistische Datenanalyse*

-   Implementierung (50%)
-   Fallstudie (50%)

*Datenanalyse in Big Data*

-   Präsentation (50%)
-   Fallstudie (50%)

*Datenbanken für Big Data*

-   Präsentation (50%)
-   Fallstudie (50%)

*Prädiktive Analytik*

-   Implementierung (50%)
-   Fallstudie (50%)

*Writing for Data Science and Engineering* (WPM)

-   Research Proposal (30%)
-   Literature Review (50%)
-   Peer-Review Report (20%)

*Big Data Anwendungsfälle*

-   Dokumentation (10%)
-   Fallstudie (90%)

*Data Science Anwendungsfälle* (WPM)

-   Dokumentation (10%)
-   Fallstudie (90%)

## Zusatz
